name: Attendize

on:
  pull_request:
    types: [assigned, edited, opened, synchronize, reopened]
  push:
    branches:
      - next
      - master
      - v2*

jobs:
  laravel-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      uses: php-actions/composer@v4
      with:
        command: install
        args: --no-ansi --prefer-dist
        php_version: 7.4
        composer_version: 1
        interaction: no
        suggest: no
        dev: yes
        progress: no
        quiet: no
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      uses: php-actions/composer@v4
      with:
        command: exec phpunit
        php_version: 7.4
        composer_version: 1
        interaction: no
        suggest: no
        dev: yes
        progress: no
        quiet: no
